/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { usePortal } from '../context/PortalContext';
import { 
  ArrowRight, Search, ShieldCheck, Plane, Ship, Truck, Globe, Award, Hourglass, Star, ChevronLeft, ChevronRight, Calculator, FileCheck2
} from 'lucide-react';
import { motion } from 'motion/react';

export const Home: React.FC = () => {
  const { setTrackingQueryId, setCurrentPage, settings, showToast } = usePortal();
  const [localTrackingId, setLocalTrackingId] = useState('');
  const [activeTestimonial, setActiveTestimonial] = useState(0);

  const handleTrackingQuery = (e: React.FormEvent) => {
    e.preventDefault();
    const cleaned = localTrackingId.trim().toUpperCase();
    if (!cleaned) {
      showToast('Please type a valid Tracking ID.', 'error');
      return;
    }
    setTrackingQueryId(cleaned);
    setCurrentPage('tracking');
    showToast(`Searching global database for ${cleaned}...`, 'info');
  };

  const handleQuickEstimate = () => {
    setCurrentPage('calculator');
  };

  const stats = [
    { value: '184+', label: 'Global Offices', icon: Globe },
    { value: '45.8K', label: 'Tons Handled/Year', icon: Plane },
    { value: '12,400', label: 'Active Containers', icon: Ship },
    { value: '99.94%', label: 'On-Time Precision', icon: Hourglass },
  ];

  const partners = [
    'Deutsche Marine Corp', 'Global Logistics Alliance', 'Air Cargo Association', 'Vance Industrial Parts', 'Apex Sourcing Ltd'
  ];

  const corePillars = [
    {
      title: 'Secure Brokerage Services',
      desc: 'Complete export/import customs administration, digital documentation, and fast clearance at all major border gates.',
      icon: ShieldCheck,
      color: 'border-l-4 border-emerald-500'
    },
    {
      title: 'Multimodal Transit Operations',
      desc: 'Seamless transit transitions from sea vessel to air freight or last-mile heavy roadway loaders.',
      icon: PlanetTransitIcon,
      color: 'border-l-4 border-[#ff3c00]'
    },
    {
      title: 'Temperature Escorted Cargo',
      desc: 'State-of-the-art cold-chain climate sensors and heavy thermal lining for delicate biological/electronic parts.',
      icon: Award,
      color: 'border-l-4 border-cyan-500'
    }
  ];

  // Dummy visual component inside file for icon
  function PlanetTransitIcon() {
    return <Globe className="h-6 w-6 text-[#ff3c00]" />;
  }

  const testimonials = [
    {
      text: "SwiftCarrier revolutionized our electronic distribution network. Customs clearances that typically took us 3 business days are now finalized in a matter of hours at Frankfurt Hub. Outstanding visibility.",
      author: "Marcus Van Halen",
      role: "Global Procurement Director, TechSolutions Europe"
    },
    {
      text: "The real-time telemetry tracking on this platform is unmatched. Being able to view container temperature readings and precise terminal coordinates gives us peace of mind for pharmaceutical goods.",
      author: "Dr. Amanda Chen",
      role: "Operations Head, Novartis Bioscience APAC"
    },
    {
      text: "Outstanding client care. When a heavy winter storm delayed our road freight transit to Chicago, the SwiftCarrier logistics desk rerouted our high-value crate onto another layout before we even noticed.",
      author: "Jameson Blake",
      role: "Heavy Machinery Sourcing Manager, Caterpillar Inc."
    }
  ];

  const processSteps = [
    { num: '01', title: 'Carriage Booked', desc: 'Consignment dimensions submitted, optimal speed route computed, customs sheets automatically generated by our portal.' },
    { num: '02', title: 'Terminal Ingest & Sort', desc: 'Secure barcoded label and active sensors attached, then sorted at regional airport, dock, or roadway hub.' },
    { num: '03', title: 'Global Multi-Transit', desc: 'Safe border crossing, regulatory customs checks, and continuous GPS telemetry tracking via central satellite systems.' },
    { num: '04', title: 'Pristine Local Hand-off', desc: 'Final sorting, out for delivery warning, signature verification, and secure client dock unload completed.' },
  ];

  const nextTestimonial = () => {
    setActiveTestimonial((prev) => (prev + 1) % testimonials.length);
  };

  const prevTestimonial = () => {
    setActiveTestimonial((prev) => (prev - 1 + testimonials.length) % testimonials.length);
  };

  return (
    <div className="font-sans text-slate-100 bg-slate-950 overflow-hidden">
      
      {/* 1. HERO MAIN SECTION */}
      <section className="relative min-h-[90vh] flex items-center justify-center bg-radial from-slate-900 via-slate-950 to-slate-950 pt-10 pb-16 px-4 border-b border-slate-900">
        
        {/* Subtle decorative grid lines */}
        <div className="absolute inset-0 bg-[linear-gradient(to_right,#0f172a_1px,transparent_1px),linear-gradient(to_bottom,#0f172a_1px,transparent_1px)] bg-[size:4rem_4rem] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_40%,#000_70%,transparent_100%)] opacity-35" />

        <div className="relative max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-12 gap-12 items-center w-full">
          
          {/* Hero Left Content */}
          <div className="lg:col-span-7 space-y-6 text-center lg:text-left z-10">
            
            {/* Tagline */}
            <span className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-mono font-semibold bg-[#ff3c00]/10 border border-[#ff3c00]/30 text-[#ff3c00] leading-none mb-3">
              <span className="h-1.5 w-1.5 rounded-full bg-[#ff3c00] animate-pulse" />
              LEADING MULTIMODAL LOGISTICS NETWORK
            </span>

            {/* Main Header Display */}
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-white tracking-tight leading-none">
              Precision Freight. <br />
              <span className="text-[#ff3c00] bg-gradient-to-r from-[#ff3c00] to-amber-500 bg-clip-text text-transparent">
                Absolute Corporate Trust.
              </span>
            </h1>

            {/* Summary */}
            <p className="text-slate-400 text-sm sm:text-base max-w-xl leading-relaxed mx-auto lg:mx-0">
              Manage your global shipping, custom declarations, cargo schedules, and live container telemetry from one modern central logistics portal. Grounded in velocity and absolute safety.
            </p>

            {/* Interactive Tracking Dock */}
            <form onSubmit={handleTrackingQuery} className="max-w-xl bg-slate-900/90 border border-slate-800 p-2.5 rounded-2xl flex flex-col sm:flex-row gap-2 shadow-2xl backdrop-blur-md">
              <div className="flex-1 flex items-center px-3 gap-2.5 bg-slate-950/80 rounded-xl border border-slate-800 focus-within:border-orange-500">
                <Search className="h-5 w-5 text-[#ff3c00]" />
                <input
                  type="text"
                  placeholder="Enter Tracking ID..."
                  value={localTrackingId}
                  onChange={(e) => setLocalTrackingId(e.target.value)}
                  className="bg-transparent text-sm text-white w-full py-3 h-full focus:outline-none placeholder-slate-600 font-mono"
                />
              </div>
              <button
                type="submit"
                className="bg-[#ff3c00] hover:bg-[#e03500] text-white px-6 py-3 font-semibold text-sm rounded-xl transition-all duration-200 shadow-md shadow-[#ff3c00]/25 flex items-center justify-center gap-1 cursor-pointer"
              >
                <span>Track Cargo</span>
                <ArrowRight className="h-4 w-4" />
              </button>
            </form>

            {/* CTA Shortcut Links */}
            <div className="flex flex-wrap items-center justify-center lg:justify-start gap-4 pt-2">
              <button
                onClick={handleQuickEstimate}
                className="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-slate-305 hover:text-white bg-slate-900 hover:bg-slate-850 px-4 py-2.5 rounded-lg border border-slate-800 cursor-pointer"
              >
                <Calculator className="h-4 w-4 text-[#ff3c00]" />
                <span>Estimate Carriage Cost</span>
              </button>
              <button
                onClick={() => setCurrentPage('services')}
                className="inline-flex items-center gap-1.5 text-xs text-slate-400 hover:text-white transition-colors cursor-pointer"
              >
                <span>Explore Multimodal Services</span>
                <ArrowRight className="h-3.5 w-3.5" />
              </button>
            </div>

          </div>

          {/* Hero Right Visual: Grid-style High-End Logistics Display */}
          <div className="lg:col-span-5 relative flex items-center justify-center">
            <div className="absolute h-96 w-96 rounded-full bg-[#ff3c00]/10 filter blur-3xl" />
            
            <div className="relative bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-2xl space-y-4 max-w-sm w-full z-10">
              {/* Feature Portrait of Air-Freighting Assets */}
              <div className="relative rounded-xl overflow-hidden border border-slate-800 shadow-inner group aspect-video">
                <img 
                  src="/src/assets/images/hero_cargo_plane_1779474879790.png" 
                  alt="SwiftCarrier Golden Hour Cargo Hub operations"
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                  referrerPolicy="no-referrer"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-slate-950/80 via-transparent to-transparent flex items-end p-3">
                  <span className="text-[10px] font-mono uppercase text-white bg-[#ff3c00] px-2 py-0.5 rounded shadow font-semibold">FLEET ASSET #A-902</span>
                </div>
              </div>

              <div className="flex items-center justify-between pb-3 border-b border-slate-800">
                <span className="text-xs font-mono text-slate-400">CARRIER CONSOLE LOGS</span>
                <span className="h-2 w-2 rounded-full bg-emerald-500" />
              </div>
              
              {/* Dynamic Mock Transit Lines */}
              <div className="space-y-3 font-mono text-[11px] text-slate-300">
                <div className="bg-slate-950 p-2.5 rounded border border-slate-900 flex items-center justify-between">
                  <div>
                    <p className="text-slate-500">FLIGHT # LH5092 (FRA-JFK)</p>
                    <p className="font-bold text-white">DEP FACILITY: FRANKFURT</p>
                  </div>
                  <Plane className="h-4 w-4 text-[#ff3c00] animate-bounce" />
                </div>

                <div className="bg-slate-950 p-2.5 rounded border border-slate-900 flex items-center justify-between">
                  <div>
                    <p className="text-slate-500">CONTAINER # MAERSK-8920</p>
                    <p className="font-bold text-slate-400">TRANSIT: NORTH PANAMA</p>
                  </div>
                  <Ship className="h-4 w-4 text-cyan-500" />
                </div>

                <div className="bg-slate-950 p-2.5 rounded border border-slate-900 flex items-center justify-between">
                  <div>
                    <p className="text-slate-500">FREIGHT TRAILER # TRK-092E</p>
                    <p className="font-bold text-slate-400">STAGE: HIGHWAY OAKLAND</p>
                  </div>
                  <Truck className="h-4 w-4 text-amber-500" />
                </div>

                <div className="bg-[#ff3c00]/5 p-2.5 rounded border border-[#ff3c00]/20 flex items-center justify-between text-[#ff3c00]">
                  <div>
                    <p className="opacity-70">TELEMETRY LOCK ACTIVE</p>
                    <p className="font-bold">STATUS: ON-TIME</p>
                  </div>
                  <ShieldCheck className="h-4 w-4" />
                </div>
              </div>

              {/* Progress Indicator Visualization */}
              <div className="pt-2">
                <div className="flex justify-between text-[11px] font-mono text-slate-400 mb-1">
                  <span>FRANKFURT RADAR</span>
                  <span>99.9% SHIELD</span>
                </div>
                <div className="h-1.5 w-full bg-slate-950 rounded-full overflow-hidden">
                  <div className="h-full bg-gradient-to-r from-orange-500 to-[#ff3c00] w-[75%] rounded-full animate-pulse" />
                </div>
              </div>

            </div>
          </div>

        </div>
      </section>

      {/* 2. TRUSTED PARTNERS LIST */}
      <section className="bg-slate-950 py-10 border-b border-slate-900 px-4">
        <div className="max-w-7xl mx-auto">
          <p className="text-center font-mono text-[10px] tracking-widest text-slate-500 uppercase mb-6">
            TRUSTED INTEGRATION LINERS & PRE-CLEARANCE PARTNERS
          </p>
          <div className="flex flex-wrap items-center justify-center gap-8 md:gap-16 opacity-45 grayscale hover:grayscale-0 transition-all">
            {partners.map((partner, idx) => (
              <span key={idx} className="font-bold font-mono tracking-tight text-sm text-slate-400 hover:text-white">
                {partner}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* 3. COHESIVE SYSTEM STATISTICS TIMER */}
      <section className="bg-slate-950 py-16 px-4">
        <div className="max-w-7xl mx-auto">
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-8">
            {stats.map((stat, idx) => {
              const Icon = stat.icon;
              return (
                <div key={idx} className="bg-slate-900/60 border border-slate-800/80 p-6 rounded-2xl flex flex-col items-center text-center shadow-lg hover:border-slate-700 transition-all">
                  <div className="p-3 bg-slate-950 text-[#ff3c00] rounded-xl mb-3.5 border border-slate-800">
                    <Icon className="h-6 w-6" />
                  </div>
                  <span className="text-2xl sm:text-4xl font-bold font-mono text-white tracking-tight">{stat.value}</span>
                  <span className="text-slate-400 text-xs mt-1.5 font-medium">{stat.label}</span>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* 3.5 GLOBAL CARRIER FLEET & LOGISTICS ASSETS SHOWCASE */}
      <section className="bg-slate-950 py-20 px-4 border-b border-slate-900">
        <div className="max-w-7xl mx-auto space-y-12">
          
          <div className="text-center max-w-2xl mx-auto space-y-3">
            <span className="text-[#ff3c00] font-mono text-xs font-bold uppercase tracking-wider border border-[#ff3c00]/30 px-3 py-1 rounded-full bg-[#ff3c00]/5">
              GLOBAL RECONNAISSANCE & CARRIAGES
            </span>
            <h2 className="text-3xl font-extrabold tracking-tight text-white sm:text-4xl leading-tight">
              Active Intermodal Transit Fleet
            </h2>
            <p className="text-slate-400 text-sm">
              We own and operate high-capacity, heavy-duty carrier assets equipped with satellite navigation, security telemetry, and real-time custom clearance APIs.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            
            {/* Asset 1: Oceanic Maritime Liner */}
            <div className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden group hover:border-[#ff3c00]/50 transition-all duration-300">
              <div className="relative aspect-video overflow-hidden">
                <img 
                  src="/src/assets/images/cargo_ship_port_1779474898870.png" 
                  alt="Ocean Freight Maritime Liner"
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                  referrerPolicy="no-referrer"
                />
                <div className="absolute top-3 left-3 bg-[#ff3c00] text-white text-[10px] font-mono font-bold px-2.5 py-1 rounded">
                  OCEAN FREIGHT
                </div>
              </div>
              <div className="p-6 space-y-2">
                <h4 className="text-lg font-bold text-white transition-colors group-hover:text-[#ff3c00]">Oceanic Post-Panamax Liners</h4>
                <p className="text-slate-400 text-xs leading-relaxed">
                  Deepwater marine operations managing heavy-machinery and bulk industrial cargo containers transiting Atlantic-Pacific trade agreements.
                </p>
                <div className="pt-2 flex justify-between items-center text-[10px] font-mono text-slate-500 border-t border-slate-800">
                  <span>DISPATCH GATEWAY: ROTTERDAM</span>
                  <span className="text-emerald-500">ACTIVE ON ROUTE</span>
                </div>
              </div>
            </div>

            {/* Asset 2: Air Cargo Lifters */}
            <div className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden group hover:border-[#ff3c00]/50 transition-all duration-300">
              <div className="relative aspect-video overflow-hidden">
                <img 
                  src="/src/assets/images/cargo_loading_1779476414448.png" 
                  alt="Air Cargo Ground Handling Operational Loader"
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                  referrerPolicy="no-referrer"
                />
                <div className="absolute top-3 left-3 bg-[#ff3c00] text-white text-[10px] font-mono font-bold px-2.5 py-1 rounded">
                  AIR FREIGHT
                </div>
              </div>
              <div className="p-6 space-y-2">
                <h4 className="text-lg font-bold text-white transition-colors group-hover:text-[#ff3c00]">Next-Gen Wide-Body Cargo Aircraft</h4>
                <p className="text-slate-400 text-xs leading-relaxed">
                  Priority express air freight transit with localized customs documentation pre-clearance directly at premium airports.
                </p>
                <div className="pt-2 flex justify-between items-center text-[10px] font-mono text-slate-500 border-t border-slate-800">
                  <span>DISPATCH GATEWAY: FRA-JFK</span>
                  <span className="text-emerald-500">99.8% ETA PRECISION</span>
                </div>
              </div>
            </div>

            {/* Asset 3: Heavy Roadway Loaders */}
            <div className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden group hover:border-[#ff3c00]/50 transition-all duration-300">
              <div className="relative aspect-video overflow-hidden">
                <img 
                  src="/src/assets/images/freight_truck_1779476380177.png" 
                  alt="Heavy Freight Roadway Trailer"
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                  referrerPolicy="no-referrer"
                />
                <div className="absolute top-3 left-3 bg-[#ff3c00] text-white text-[10px] font-mono font-bold px-2.5 py-1 rounded">
                  ROAD FREIGHT
                </div>
              </div>
              <div className="p-6 space-y-2">
                <h4 className="text-lg font-bold text-white transition-colors group-hover:text-[#ff3c00]">Autonomous Telemetry Freight Trucks</h4>
                <p className="text-slate-400 text-xs leading-relaxed">
                  Climate-escorted temperature-sensitive inland distribution corridors bridging seaports directly to central storage warehouses.
                </p>
                <div className="pt-2 flex justify-between items-center text-[10px] font-mono text-slate-500 border-t border-slate-800">
                  <span>TRANSIT CORRIDOR: INTERSTATE 90</span>
                  <span className="text-[#ff3c00]">TEMPERATURE ESCORTED</span>
                </div>
              </div>
            </div>

            {/* Asset 4: Intelligent Storage Environments */}
            <div className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden group hover:border-[#ff3c00]/50 transition-all duration-300">
              <div className="relative aspect-video overflow-hidden">
                <img 
                  src="/src/assets/images/warehouse_operations_1779474916748.png" 
                  alt="Smart Warehouse Operations Dispatch Depot"
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                  referrerPolicy="no-referrer"
                />
                <div className="absolute top-3 left-3 bg-[#ff3c00] text-white text-[10px] font-mono font-bold px-2.5 py-1 rounded">
                  WAREHOUSE DEPOT
                </div>
              </div>
              <div className="p-6 space-y-2">
                <h4 className="text-lg font-bold text-white transition-colors group-hover:text-[#ff3c00]">Smart Fulfillment & Sorting Centers</h4>
                <p className="text-slate-400 text-xs leading-relaxed">
                  Automated computer-vision sorting platforms, real-time customs checkpoints, cargo scales, and digital cross-docking operations.
                </p>
                <div className="pt-2 flex justify-between items-center text-[10px] font-mono text-slate-500 border-t border-slate-800">
                  <span>FACILITY CAPACITY: 8.4M TONS</span>
                  <span className="text-emerald-500">FULLY SECURED HUB</span>
                </div>
              </div>
            </div>

            {/* Asset 5: Ocean Terminal Container Stacks */}
            <div className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden group hover:border-[#ff3c00]/50 transition-all duration-300">
              <div className="relative aspect-video overflow-hidden">
                <img 
                  src="/src/assets/images/containers_port_1779476430701.png" 
                  alt="Neatly Stacked Maritime Cargo Containers"
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                  referrerPolicy="no-referrer"
                />
                <div className="absolute top-3 left-3 bg-[#ff3c00] text-white text-[10px] font-mono font-bold px-2.5 py-1 rounded">
                  CONTAINER PORT
                </div>
              </div>
              <div className="p-6 space-y-2">
                <h4 className="text-lg font-bold text-white transition-colors group-hover:text-[#ff3c00]">Customs-Clearance Buffer Yards</h4>
                <p className="text-slate-400 text-xs leading-relaxed">
                  Intermodal logistic depots optimizing empty container hand-offs and container pre-clearance with local border authorities.
                </p>
                <div className="pt-2 flex justify-between items-center text-[10px] font-mono text-slate-500 border-t border-slate-800">
                  <span>FACILITY CAPACITY: 24,000 TEU</span>
                  <span className="text-emerald-500">SATELLITE ESCORTED</span>
                </div>
              </div>
            </div>

            {/* Asset 6: Last-Mile Electric Dispatch */}
            <div className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden group hover:border-[#ff3c00]/50 transition-all duration-300">
              <div className="relative aspect-video overflow-hidden">
                <img 
                  src="/src/assets/images/delivery_worker_1779476396729.png" 
                  alt="Delivery worker next to an electric delivery van"
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                  referrerPolicy="no-referrer"
                />
                <div className="absolute top-3 left-3 bg-[#ff3c00] text-white text-[10px] font-mono font-bold px-2.5 py-1 rounded">
                  LAST MILE DELIVERY
                </div>
              </div>
              <div className="p-6 space-y-2">
                <h4 className="text-lg font-bold text-white transition-colors group-hover:text-[#ff3c00]">Corporate Consignment Couriers</h4>
                <p className="text-slate-400 text-xs leading-relaxed">
                  Pruned delivery networks utilizing zero-emission vans to transport document waybills and pallets to corporate client docks.
                </p>
                <div className="pt-2 flex justify-between items-center text-[10px] font-mono text-slate-500 border-t border-slate-800">
                  <span>LAST-MILE COURIERS: ACTIVE</span>
                  <span className="text-emerald-500">SIGNATURE GUARANTEE</span>
                </div>
              </div>
            </div>

          </div>

        </div>
      </section>

      {/* 4. SHIPMENT LIFECYCLE PROGRESS SHOWCASE */}
      <section className="bg-slate-900/30 border-y border-slate-900 py-20 px-4 relative">
        <div className="absolute inset-0 bg-[#ff3c00]/1 at-top-center mask-radial pointer-events-none" />
        
        <div className="max-w-7xl mx-auto">
          
          <div className="max-w-2xl mx-auto text-center mb-16 space-y-3">
            <span className="text-[#ff3c00] font-mono text-xs font-bold uppercase tracking-wider">
              PRISTINE CHAIN OF ESCORT
            </span>
            <h2 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">
              How We Escort Your Cargo Safely
            </h2>
            <p className="text-slate-400 text-sm">
              From instant digital tariff booking to final delivery validation. We operate on a standardized framework to suppress transit delays.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {processSteps.map((step, idx) => (
              <div key={idx} className="relative group bg-slate-900 border border-slate-800 p-6 rounded-2xl shadow-xl transition-all hover:-translate-y-1 hover:border-slate-700">
                
                {/* Large index digit */}
                <span className="absolute top-4 right-4 text-5xl font-mono font-bold text-slate-800/40 select-none group-hover:text-[#ff3c00]/10 transition-colors">
                  {step.num}
                </span>

                <div className="relative space-y-4">
                  <div className="inline-flex h-9 w-9 items-center justify-center rounded-lg bg-[#ff3c00]/10 border border-[#ff3c00]/30 text-[#ff3c00] text-sm font-mono font-extrabold shadow-inner">
                    {step.num}
                  </div>
                  <h4 className="text-lg font-bold text-white font-sans">
                    {step.title}
                  </h4>
                  <p className="text-slate-400 text-xs leading-relaxed">
                    {step.desc}
                  </p>
                </div>
              </div>
            ))}
          </div>

        </div>
      </section>

      {/* 5. WHY CHOOSE SYSTEM PILLARS */}
      <section className="bg-slate-950 py-20 px-4">
        <div className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
          
          {/* Why Left */}
          <div className="lg:col-span-5 space-y-5">
            <span className="text-[#ff3c00] font-mono text-xs font-bold uppercase tracking-wider">
              ADVANCED SAFEGUARDS
            </span>
            <h3 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight leading-tight">
              Enterprise Carriage Standard Operating Controls.
            </h3>
            <p className="text-slate-400 text-sm leading-relaxed">
              We treat cargo shipping as a high-security cryptographic operation rather than simple cargo transportation. Every crate is accounted for down to the second.
            </p>
            <div className="pt-4 flex">
              <button
                onClick={() => setCurrentPage('about')}
                className="bg-slate-900 text-white font-semibold text-xs uppercase tracking-wider border border-slate-800 hover:border-slate-700 px-5 py-3 rounded-lg flex items-center gap-1.5 cursor-pointer"
              >
                <FileCheck2 className="h-4 w-4 text-[#ff3c00]" />
                <span>Verify Compliance Credentials</span>
              </button>
            </div>
          </div>

          {/* Why Right */}
          <div className="lg:col-span-7 space-y-4">
            {corePillars.map((pillar, idx) => {
              const Icon = pillar.icon;
              return (
                <div key={idx} className={`bg-slate-905 bg-slate-900 border border-slate-800 rounded-2xl p-6 flex gap-4 ${pillar.color}`}>
                  <div className="p-3 bg-slate-950 rounded-xl max-h-fit border border-slate-850">
                    <Icon />
                  </div>
                  <div className="space-y-1">
                    <h5 className="font-bold text-white text-base font-sans">{pillar.title}</h5>
                    <p className="text-slate-400 text-xs leading-relaxed">{pillar.desc}</p>
                  </div>
                </div>
              );
            })}
          </div>

        </div>
      </section>

      {/* 6. GLOBAL ROUTING MAP SECTION */}
      <section className="bg-slate-900/10 border-y border-slate-950 py-20 px-4 relative overflow-hidden bg-radial from-slate-900 to-slate-950">
        <div className="max-w-7xl mx-auto text-center space-y-12">
          
          <div className="max-w-xl mx-auto space-y-2">
            <span className="text-[#ff3c00] font-mono text-xs font-bold uppercase tracking-wider">
              ESTABLISHED CARRIAGE LANES
            </span>
            <h4 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
              A Wide Global Supply Web
            </h4>
            <p className="text-slate-400 text-xs">
              Continuous vessel flow between North Atlantic gateways, Asian hubs, and Transpacific cargo corridors.
            </p>
          </div>

          {/* Sincere SVG World Network Map */}
          <div className="relative bg-slate-900/30 border border-slate-850 rounded-3xl p-4 md:p-8 flex items-center justify-center max-w-4xl mx-auto overflow-hidden">
            <svg viewBox="0 0 1000 500" className="w-[100%] h-auto opacity-70 filter drop-shadow-[0_0_15px_rgba(255,60,0,0.15)] select-none pointer-events-none">
              
              {/* Background map simplified paths */}
              {/* Continents outlines */}
              <path d="M150 150 Q180 120 220 150 T280 180 T300 230 Q280 280 260 300 T210 330 Z" fill="#1e293b" opacity="0.4" />
              <path d="M500 120 Q560 90 620 120 T700 150 T800 200 Q780 280 730 350 T650 384 Z" fill="#1e293b" opacity="0.4" />
              <path d="M350 250 Q400 280 430 350 T450 450 Q380 460 350 420 Z" fill="#1e293b" opacity="0.4" />
              <path d="M480 200 Q510 220 520 280 T560 350 Q520 380 490 320 Z" fill="#1e293b" opacity="0.4" />
              
              {/* Core Airport Air Hub dots */}
              <circle cx="250" cy="180" r="5" fill="#ff3c00" /> {/* New York */}
              <circle cx="480" cy="150" r="5" fill="#ff3c00" /> {/* Frankfurt */}
              <circle cx="450" cy="180" r="4" fill="#ff3c00" /> {/* London */}
              <circle cx="780" cy="210" r="5" fill="#ff3c00" /> {/* Tokyo */}
              <circle cx="710" cy="260" r="4" fill="#ff3c00" /> {/* Shanghai */}
              <circle cx="790" cy="380" r="4" fill="#ff3c00" /> {/* Sydney */}

              {/* Hub Label Flags */}
              <text x="250" y="170" fill="#cbd5e1" fontSize="10" fontFamily="monospace" textAnchor="middle">JFK</text>
              <text x="480" y="140" fill="#cbd5e1" fontSize="10" fontFamily="monospace" textAnchor="middle">FRA</text>
              <text x="450" y="195" fill="#cbd5e1" fontSize="10" fontFamily="monospace" textAnchor="middle">LHR</text>
              <text x="780" y="200" fill="#cbd5e1" fontSize="10" fontFamily="monospace" textAnchor="middle">NRT</text>
              <text x="710" y="250" fill="#cbd5e1" fontSize="10" fontFamily="monospace" textAnchor="middle">CNSHA</text>
              <text x="790" y="370" fill="#cbd5e1" fontSize="10" fontFamily="monospace" textAnchor="middle">SYD</text>

              {/* Transit Curved lines (Air Corridors) */}
              <path d="M250 180 Q350 140 450 180" fill="none" stroke="#ff3c00" strokeWidth="1.5" strokeDasharray="5,5" />
              <path d="M450 180 Q465 165 480 150" fill="none" stroke="#ff3c00" strokeWidth="1.5" strokeDasharray="3,3" />
              <path d="M480 150 Q630 150 780 210" fill="none" stroke="#ff3c00" strokeWidth="1.5" strokeDasharray="5,5" />
              <path d="M710 260 Q750 320 790 380" fill="none" stroke="#ff3c00" strokeWidth="1.5" strokeDasharray="5,5" />
              <path d="M710 260 Q485 220 250 180" fill="none" stroke="cyan" strokeWidth="1.2" opacity="0.6" />

              {/* Radar Sweeper */}
              <circle cx="480" cy="150" r="100" fill="none" stroke="#ff3c00" strokeWidth="0.5" opacity="0.15" />
              <circle cx="480" cy="150" r="220" fill="none" stroke="#ff3c00" strokeWidth="0.5" opacity="0.08" />

            </svg>
            
            <div className="absolute bottom-4 left-4 flex gap-6 text-[10px] sm:text-xs font-mono text-slate-400 bg-slate-950/90 py-1.5 px-3 rounded border border-slate-800">
              <span className="flex items-center gap-1.5">
                <span className="h-2.5 w-2.5 bg-[#ff3c00] rounded-sm" /> Express Lane
              </span>
              <span className="flex items-center gap-1.5">
                <span className="h-2.5 w-2.5 bg-cyan-400 rounded-sm" /> Ocean Sea Route
              </span>
            </div>
          </div>

        </div>
      </section>

      {/* 7. CUSTOM ACCOUNTABLE TESTIMONIALS SLIDER */}
      <section className="bg-slate-950 py-20 px-4">
        <div className="max-w-5xl mx-auto bg-slate-900 border border-slate-800 rounded-3xl p-8 md:p-12 shadow-2xl relative">
          
          <div className="absolute top-6 left-8 text-7xl font-serif text-[#ff3c00]/10 select-none">
            “
          </div>

          <div className="relative flex flex-col justify-between h-full min-h-[220px]">
            <div className="space-y-4">
              <div className="flex text-amber-500">
                {[...Array(5)].map((_, i) => (
                  <Star key={i} className="h-4.5 w-4.5 fill-amber-500 text-amber-500" />
                ))}
              </div>
              <p className="text-white text-md sm:text-xl font-medium leading-relaxed italic">
                "{testimonials[activeTestimonial].text}"
              </p>
            </div>

            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center pt-8 border-t border-slate-800/60 mt-8 gap-4">
              <div>
                <h5 className="font-bold text-white text-base">
                  {testimonials[activeTestimonial].author}
                </h5>
                <p className="text-[#ff3c00] text-xs font-mono">
                  {testimonials[activeTestimonial].role}
                </p>
              </div>

              {/* Slider Toggles */}
              <div className="flex gap-2">
                <button
                  onClick={prevTestimonial}
                  className="p-2.5 bg-slate-950 border border-slate-800 hover:border-slate-700 text-slate-350 hover:text-white rounded-lg transition-colors cursor-pointer"
                >
                  <ChevronLeft className="h-4 w-4" />
                </button>
                <button
                  onClick={nextTestimonial}
                  className="p-2.5 bg-slate-950 border border-slate-800 hover:border-slate-700 text-slate-350 hover:text-white rounded-lg transition-colors cursor-pointer"
                >
                  <ChevronRight className="h-4 w-4" />
                </button>
              </div>
            </div>

          </div>
        </div>
      </section>

    </div>
  );
};
